config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :posts do
    resources :comments
  end

  get 'users/show'
  get ':name', to: 'users#show', as: :profile
  get ':name/avatar', to: 'users#avatar', as: :user_avatar

  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  validates :user_id, presence: true

  validates :image, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, styles: { small: "100x100", med: "300x300", large: "500x500" }
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Adding more flash types for bootstrap styling (defaults- :alert, :notice)
  add_flash_types :danger, :warning, :success, :validation_errors
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to authenticated_root_path }
        format.js
      end
    else
      flash[:danger] = "Something went wrong and your comment wasn't created."
      render authenticated_root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to authenticated_root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.order('created_at DESC')
    @post = current_user.posts.build
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:danger] = "Your new post couldn't be created! Please check the form."
      redirect_to :back
    end
  end

  def edit
  end

  def show
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:danger] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
    flash[:success] = "Post deleted"
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:warning] = "That post doesn't belong to you!"
      redirect_to authenticated_root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # overriding the devise after sign up path method
  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end

  # overriding the devise after sign in path method
  def after_sign_in_path_for(resource)
    authenticated_root_path
  end

  private

  # Devise strong params for accepting newly added params
  # If a param isn't added here, it won't be saved to DB
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  # defining what user params can be updated
  def account_update_params
    params.require(:user).permit(:password, :password_confirmation, :name, :dob, :sex, :location, :about, :art_style, :avatar)
  end

  # allow user to update their info without password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def show
    @user = User.find_by(name: params[:name])
    @post = current_user.posts.build
    @posts = User.find_by(name: params[:name]).posts.order('created_at DESC')
  end

  def avatar
  end

  private

  def set_user
    @user = User.find_by(name: params[:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # This helper calculates age from a user's DOB
  def age(dob)
    (Date.today - dob).to_i / 365
  end

  # Helper to display how long ago a post was created
  def how_long_ago(post)
    if post.created_at > Time.now.beginning_of_day
      "Posted " + time_ago_in_words(post.created_at) + " ago"
    else
      "Posted on " + post.created_at.strftime("%b %d, %Y")
    end
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  
  # Helper for adding bootstrap styles to devise error msgs
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable"> <button type="button"
     class="close" data-dismiss="alert">x</button>
     <h4>#{sentence}</h4>
     #{messages}
    </div>
    HTML

    html.html_safe
  end

end

app/views/comments/_comment.html.erb
<div class="comments">
  <div class="row">
    <div class="col-sm-2">

      <div class="dropdown drop-menu">
        <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown">
          <% if comment.user.avatar.exists? %>
            <%= image_tag comment.user.avatar, class: 'tiny-img pull-left img-responsive' %>
          <% else %>
            <%= image_tag 'user.png', class: 'tiny-img pull-left img-responsive' %>
          <% end %>
        </button>
        <ul class="dropdown-menu drop-content">
          <% if comment.user.id == current_user.id %>
            <li class="dropdown-header"><%= comment.user.name %></li>
            <li class="divider"></li>
            <li><%= link_to 'View Profile', profile_path(comment.user.name) %></li>
          <% else %>
            <li class="dropdown-header"><%= comment.user.name %></li>
            <li class="divider"></li>
            <li><%= link_to 'View Profile', profile_path(comment.user.name) %></li>
            <li><%= link_to 'Add Friend', '#' %></li>
            <li><%= link_to 'Block User', '#' %></li>
          <% end %>
        </ul>
      </div>

    </div>

    <div class="col-sm-8">
      <div class="caption">
        <% if comment.content.length > 50 %>
          <div id="trunc-comment-<%= comment.id %>">
            <%= truncate(comment.content, length: 50) %>
            <%= link_to 'Read more', '#', remote: true, class: 'show-more', data: {comment_id: "#{comment.id}", type: "html"} %>
          </div>

          <div id="nontrunc-comment-<%= comment.id %>" class="hidden post-caption">
            <%= comment.content %>
            <%= link_to 'Read less', '#', remote: true, class: 'show-less', data: {comment_id: "#{comment.id}", type: "html"} %>
          </div>
        <% else %>
          <%= comment.content %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-2">

      <% if comment.user.id == current_user.id %>
        <div class="dropdown comment-options">
          <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown">
            <%= image_tag 'threedot.png', class: 'img-responsive three-dot' %>
          </button>
          <ul class="dropdown-menu user-menu">
            <li><%= link_to 'Delete comment', post_comment_path(post, comment), method: :delete, remote: true, data: {confirm: 'Are you sure you want to delete this comment?'} %></li>
          </ul>
        </div>
      <% else %>
        <div class="dropdown">
          <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown"><%= image_tag 'threedot.png', class: 'img-responsive three-dot' %></button>
          <ul class="dropdown-menu user-menu">
            <li><%= link_to 'Report inappropriate content', '#' %></li>
          </ul>
        </div>
      <% end %>

    </div>

  </div> <!-- row end -->
</div>
<div class="clearfix"></div>

app/views/comments/create.js.erb
// AJAX response for comments controller create method
// appends comments onto the post and resets text field
$('#comment-content-<%= @post.id %>, input[type="text"]').val('');
$('#comments-<%= @post.id %>').append("<%= j render 'comments/comment', post: @post, comment: @comment %>");

app/views/layouts/_alert.html.erb
<div class="alert
  <%= case type.to_sym
        when :alert, :danger, :validation_errors
            'alert-danger'        # red
        when :warning
            'alert-warning'       # yellow
        when :notice, :success
            'alert-success'       # green
        else
            'alert-info'          # blue
      end %>
alert-dismissible" role="alert">


    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>

</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'News Feed', authenticated_root_path %></li>
          <% if current_user.name != nil %>
            <li><%= link_to 'Profile', profile_path(current_user.name) %></li>
          <% end %>
          <li><%= link_to 'Settings', edit_user_registration_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
<% end %>

app/views/layouts/_welcome.html.erb
<div class="text-center">
  <h2>Welcome to MuseFinder</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <hr>
</div> <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseFinder</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
  <script src="jquery.geocomplete.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="container text-center">
    <h1 id="musefinder">MuseFinder</h1>
    <p><i>Find Your Art Muse</i></p>
  </div>
</header>

<%= render 'layouts/navbar' %>

<!-- include: remote: true, data: {toggle: 'modal', target: '#myModal'} -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center"></h4>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

<section>
  <div class="container">

    <div class="alert-msgs">
        <% flash.each do |type, content| %>
          <% if content.respond_to?('each')
              content.each do |item| %>
                <%= render 'layouts/alert', type: type, content: item %>
              <% end %>
          <% else %>
              <%= render 'layouts/alert', type: type, content: content %>
          <% end %>
        <% end %>
    </div>

    <%= yield %>

  </div>
</section>

<footer>
  <div class="container">
    <p>MuseFinder Copyright &copy, 2017</p>
  </div>
</footer>

</body>
</html>

app/views/posts/_edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit this post</h3>
  </div>
  <div class="panel-body">
    <%= form_for @post, html: { multipart: true } do |f| %>
      <%= image_tag @post.image, class: 'img-responsive post-img' %> <br>
      <div class="form-group">
        <%= f.text_area :caption, placeholder: 'Write a short caption for your image', class: 'form-control', autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.submit "Update", class: 'btn btn-success' %>
        <div class="pull-right">
          <label class="btn btn-primary btn-file">
            Choose Image<%= f.file_field :image, style: 'display:none;' %>
          </label>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center">
  <%= link_to 'Cancel', :back %> 
</div>

app/views/posts/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create a post</h3>
  </div>
  <div class="panel-body">
    <%= form_for @post, html: { multipart: true } do |f| %>

      <div class="form-group">
        <%= f.text_area :caption, placeholder: 'Write a short caption for your image', class: 'form-control', autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.submit "Post", class: 'btn btn-success' %>
        <div class="pull-right">
          <label class="btn btn-primary btn-file">
            Choose Image<%= f.file_field :image, style: 'display:none;' %>
          </label>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_new.html.erb
<%= render 'posts/form' %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="panel panel-default post">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to post.user.name, profile_path(post.user.name) %></h3>
  </div>

  <div class="panel-body">
    <%= link_to post_path(post), remote: true, data: {toggle: 'modal', target: '#myModal'} do %>
      <%= image_tag post.image, class: 'img-responsive post-img' %> <hr>
    <% end %>

      <div class="row">
        <div class="col-sm-6">
          <div class="pull-left">
            <%= how_long_ago(post) %>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="likes pull-right">1000 Likes</div>
        </div> <br> <br>

    <!-- post caption !!!!!!!!!!!!!!!!!!!!!!!!!!!-->
        <div class="col-sm-2">
          <div class="dropdown drop-menu">
            <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown">
              <% if post.user.avatar.exists? %>
                <%= image_tag post.user.avatar, class: 'tiny-img pull-left img-responsive' %>
              <% else %>
                <%= image_tag 'user.png', class: 'tiny-img pull-left img-responsive' %>
              <% end %>
            </button>
            <ul class="dropdown-menu drop-content">
              <% if post.user.id == current_user.id %>
                <li class="dropdown-header"><%= post.user.name %></li>
                <li class="divider"></li>
                <li><%= link_to 'View Profile', profile_path(post.user.name) %></li>
              <% else %>
                <li class="dropdown-header"><%= post.user.name %></li>
                <li class="divider"></li>
                <li><%= link_to 'View Profile', profile_path(post.user.name) %></li>
                <li><%= link_to 'Add Friend', '#' %></li>
                <li><%= link_to 'Block User', '#' %></li>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="col-sm-10">
          <div class="caption">
            <% if post.caption.length > 50 %>
              <div id="trunc-<%= post.id %>">
                <%= truncate(post.caption, length: 50) %>
                <%= link_to 'Read more', '#', remote: true, class: 'more', data: {post_id: "#{post.id}", type: "html"} %>
              </div>

              <div id="nontrunc-<%= post.id %>" class="hidden post-caption">
                <%= post.caption %>
                <%= link_to 'Read less', '#', remote: true, class: 'less', data: {post_id: "#{post.id}", type: "html"} %>
              </div>
            <% else %>
              <%= post.caption %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"></div><br>
    <!-- end post caption !!!!!!!!!!!!!!!!!!!!!!!!!-->
    <!-- comment form !!!!!!!!!!!!!!!!!!!!!!!!!!!-->
      <div class="col-sm-12">
        <%= form_for [post, post.comments.build], remote: true do |f| %>
          <div class="form-group">
            <%= f.text_field :content, placeholder: 'Comment on this post...', class: 'form-control', id: 'comment-content-#{post.id}' %>
          </div>
          <div class="clearfix"></div><hr>
        <% end %>
      </div>
   <!-- end comment form !!!!!!!!!!!!!!!!!!!!!!!!!-->
   <!-- user comments !!!!!!!!!!!!!!!!!!!!!!!!!!!-->
      <div id="show-<%= post.id %>" class="text-center">
        <%= link_to 'Show comments', '#', remote: true, class: 'show-comments', data: {post_id: "#{post.id}", type: "html"} %>
      </div>

      <div id="hide-<%= post.id %>" class="text-center hidden">
        <%= link_to 'Hide comments', '#', remote: true, class: 'hide-comments', data: {post_id: "#{post.id}", type: "html"} %>
      </div>

      <div id="comments-<%= post.id %>" class="comments hidden">
        <% if post.comments.any? %>
          <% post.comments.each do |comment| %>
            <%= render post.comments.order('created_at ASC'), post: post %>
          <% end %>
        <% end %>
      </div>

  </div> <hr> <!-- end row -->
 <!-- end user comments !!!!!!!!!!!!!!!!!!!!!!!!!!!-->

    <div class="pull-right">
      <% if post.user.id == current_user.id %>
        <div class="dropdown">
          <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown">
            <%= image_tag 'threedot.png', class: 'img-responsive three-dot' %>
          </button>
          <ul class="dropdown-menu user-menu">
            <li><%= link_to 'Edit post', edit_post_path(post), remote: true, data: {toggle: 'modal', target: '#myModal'} %></li>
            <li><%= link_to 'Delete post', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %></li>
          </ul>
        </div>
      <% else %>
        <div class="dropdown">
          <button class="dropdown-toggle option-btn" type="button" data-toggle="dropdown"><%= image_tag 'threedot.png', class: 'img-responsive three-dot' %></button>
          <ul class="dropdown-menu user-menu">
            <li><%= link_to 'Hide this post', '#', class: 'hide-post', remote: true, data: {post_id: "#{post.id}", type: "html"} %></li>
            <li><%= link_to 'Report inappropriate content', '#' %></li>
          </ul>
        </div>
      <% end %>
    </div>

  </div> <!-- end panel-body -->
</div> <!-- end panel -->

<div style="margin-bottom:20px;" id="unhide-<%= post.id %>" class="hidden">
  This post has been hidden. <%= link_to 'Click here', '#', class: 'unhide-post', remote: true, data: {post_id: "#{post.id}", type: "html"} %> to unhide it.
</div>

app/views/posts/_show.html.erb
<%= image_tag @post.image, class: 'img-responsive img-modal' %>

app/views/posts/edit.js.erb
// AJAX response for opening the 'edit' partial in a modal
$('.modal-title').html('Edit Post');
$('.modal-body').html('<%= j render("edit") %>');

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-6">
    <%= render 'new' %>

    <div class="row">
      <div class="col-md-12">
        <% @posts.each do |post| %>
          <%= render 'post', post: post %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <%= render 'users/myfriends' %>
    <%= render 'users/chats' %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/posts/show.js.erb
// AJAX response for opening the 'show' partial in a modal
$('.modal-title').html('<div style="word-wrap:break-word; margin-right:20px;"><%= @post.caption %></div>');
$('.modal-body').html('<%= j render("show") %>');

app/views/users/_avatar.html.erb
<% if @user.avatar.exists? %>
  <%= image_tag(@user.avatar, class: 'img-responsive img-modal') %>
<% else %>
  <%= image_tag('user.png', class: 'img-responsive img-modal') %>
<% end %>

app/views/users/_chats.html.erb
<div class="panel panel-default groups">
  <div class="panel-heading">
    <h3 class="panel-title">Chats</h3>
  </div>
  <div class="panel-body">

    <div class="group-item">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to '#' do %>
            <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <div class="bubble">
            <div class="pointer">
              <p>This is a paragraph of intro text, or whatever I want to call it...</p>
            </div>
            <div class="pointer-border"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="group-item">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to '#' do %>
            <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <div class="bubble">
            <div class="pointer">
              <p>This is a paragraph of intro text, or whatever I want to call it...</p>
            </div>
            <div class="pointer-border"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="group-item">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to '#' do %>
            <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <div class="bubble">
            <div class="pointer">
              <p>This is a paragraph of intro text, or whatever I want to call it...</p>
            </div>
            <div class="pointer-border"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <a href="#" class="btn btn-primary">View All Chats</a>
  </div>
</div>

app/views/users/_myfriends.html.erb
<div class="panel panel-default friends">
  <div class="panel-heading">
    <h3 class="panel-title">My Friends</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

      <li>
        <%= link_to '#' do %>
          <%= image_tag 'user.png', class: 'img-responsive thumbnail' %>
        <% end %>
      </li>

    </ul>
    <div class="clearfix"></div>
    <a class="btn btn-primary" href="#">View All Friends</a>
  </div>
</div>

app/views/users/avatar.js.erb
// AJAX response for opening the 'avatar' partial in a modal
$('.modal-title').html('<%= @user.name %>');
$('.modal-body').html('<%= j render("avatar") %>');

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-6">
    <div class="profile">
      <h1 class="page-header"><%= @user.name %></h1>
      <div class="row">
        <div class="col-md-4">
          <% if @user.avatar.exists? %>
            <%= link_to user_avatar_path(@user.name), remote: true, data: {toggle: 'modal', target: '#myModal'} do %>
              <%= image_tag(@user.avatar, class: 'img-responsive img-thumbnail') %>
            <% end %>
          <% else %>
            <%= link_to user_avatar_path(@user.name), remote: true, data: {toggle: 'modal', target: '#myModal'} do %>
              <%= image_tag('user.png', class: 'img-responsive img-thumbnail') %>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-8">
          <ul>
            <% if @user.name != nil %>
              <li><strong>Name:</strong> <%= @user.name %></li>
            <% else %>
              <li><strong>Name:</strong></li>
            <% end %>

            <% if @user.location != nil %>
              <li><strong>Location:</strong> <%= @user.location %></li>
            <% else %>
              <li><strong>Location:</strong></li>
            <% end %>

            <% if @user.sex != nil %>
              <li><strong>Gender:</strong> <%= @user.sex %></li>
            <% else %>
              <li><strong>Gender:</strong></li>
            <% end %>

            <% if @user.dob != nil %>
              <li><strong>Age:</strong> <%= age(@user.dob) %></li>
            <% else %>
              <li><strong>Age:</strong></li>
            <% end %>

            <% if @user.art_style != nil %>
              <li><strong>Art Style:</strong> <%= @user.art_style %></li>
            <% else %>
              <li><strong>Art Style:</strong></li>
            <% end %>

            <% if @user.about != nil %>
              <li class="about"><strong>About:</strong><span id="user-info"><%= @user.about %></span></li>
            <% else %>
              <li><strong>About:</strong></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div> <br>
    <div class="row">
      <div class="col-md-12">
        <% if current_user == @user %>
          <%= render 'posts/new' %>
        <% end %> <br>

        <div class="row">
          <div class="col-md-12">
            <% @posts.each do |post| %>
              <%= render 'posts/post', post: post %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'myfriends' %>
    <%= render 'chats' %>
  </div>
  <div class="col-md-1"></div>
</div>